### ISSUE TITLE
Remove `palette` dependency

### ISSUE THREAD

**Issue by ocramz** [ocramz/plot-light#1]
This dependency doesn't build with GHC 8.2.1 , which prevents `plot-light` from being included in Stackage LTS

**Comment by tonyday567** [comment]
I'm just checking this https://github.com/fpco/stackage/issues/2869

**Comment by ocramz** [comment]
Hey @tonyday567 , good catch. I don't know a good way to solve this in general and don't have that much time to investigate it in detail. Since my library here doesn't strictly require `palette` but just a way to generate color ranges, I'll remove the dependency by next version.

**Comment by ocramz** [comment]
Removed `palette` dependency in 0.3, will generate colour ranges as they are needed.
