### ISSUE TITLE
Build against attoparsec-time-1

### ISSUE THREAD

**Issue by DanBurton** [ocramz/plot-light#2]
Build failure as seen on the Stackage build server:

```
[1 of 1] Compiling Main             ( app/timeseries/Main.hs, dist/build/timeseries/timeseries-tmp/Main.o )

app/timeseries/Main.hs:10:1: error:
    Could not find module ‘Attoparsec.Time’
    Use -v to see a list of the files searched for.
   |
10 | import qualified Attoparsec.Time as AT
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Apparently this module was removed in version 1. I will add an upper bound on Stackage for attoparsec-time; ping a stackage curator when plot-light has released a version compatible with the latest attoparsec-time so that we can unconstrain it.

**Comment by ocramz** [comment]
Thank you @DanBurton ! I'll fix this asap.
